import type { ClosetItem, Combination } from '@mei/types';

const USER_ID = 'u_demo';
const NOW = '2026-04-27T09:00:00.000Z';

function item(
  partial: Pick<ClosetItem, 'itemId' | 'category' | 'name' | 'description'> &
    Partial<ClosetItem>,
): ClosetItem {
  return {
    userId: USER_ID,
    colors: [],
    occasionTags: [],
    weatherTags: [],
    rawPhotoUrl: '',
    tunedPhotoUrl: '',
    thumbnailUrl: '',
    status: 'READY',
    createdAt: NOW,
    updatedAt: NOW,
    ...partial,
  };
}

export const mockItems: ClosetItem[] = [
  item({
    itemId: 'i_dress_linen',
    category: 'DRESS',
    name: 'Cream linen midi',
    description: 'Sleeveless A-line in soft cream linen.',
    colors: ['#F2EAD9'],
    occasionTags: ['BRUNCH', 'CASUAL'],
    weatherTags: ['HOT', 'WARM'],
  }),
  item({
    itemId: 'i_dress_floral',
    category: 'DRESS',
    name: 'Floral wrap',
    description: 'Tea-length wrap in dusty mauve floral.',
    colors: ['#E5D5E0'],
    occasionTags: ['DATE', 'WEDDING'],
    weatherTags: ['WARM'],
  }),
  item({
    itemId: 'i_top_silk',
    category: 'TOP',
    name: 'Ivory silk camisole',
    description: 'Bias-cut camisole with thin straps.',
    colors: ['#F2EAD9'],
    occasionTags: ['EVENING', 'DATE'],
    weatherTags: ['MILD', 'WARM'],
  }),
  item({
    itemId: 'i_top_tee',
    category: 'TOP',
    name: 'White boxy tee',
    description: 'Heavy cotton tee, slightly cropped.',
    colors: ['#FFFFFF'],
    occasionTags: ['CASUAL'],
    weatherTags: ['HOT', 'WARM'],
    status: 'PROCESSING',
  }),
  item({
    itemId: 'i_top_blouse',
    category: 'TOP',
    name: 'Sage button-down',
    description: 'Oversized sage poplin shirt.',
    colors: ['#D5DDD0'],
    occasionTags: ['WORK', 'BRUNCH'],
    weatherTags: ['MILD'],
  }),
  item({
    itemId: 'i_bottom_jeans',
    category: 'BOTTOM',
    name: 'Indigo straight jeans',
    description: 'Mid-rise straight leg in raw indigo.',
    colors: ['#3D4856'],
    occasionTags: ['CASUAL', 'WORK'],
    weatherTags: ['MILD', 'COLD'],
  }),
  item({
    itemId: 'i_bottom_skirt',
    category: 'BOTTOM',
    name: 'Tan pleated skirt',
    description: 'Knee-length pleated skirt in warm tan.',
    colors: ['#DCC9B6'],
    occasionTags: ['WORK', 'DATE'],
    weatherTags: ['MILD'],
  }),
  item({
    itemId: 'i_bottom_shorts',
    category: 'BOTTOM',
    name: 'Linen shorts',
    description: 'High-rise tailored shorts in oat linen.',
    colors: ['#F2EAD9'],
    occasionTags: ['BRUNCH', 'BEACH'],
    weatherTags: ['HOT'],
    status: 'PROCESSING',
  }),
  item({
    itemId: 'i_outer_blazer',
    category: 'OUTERWEAR',
    name: 'Tan blazer',
    description: 'Single-breasted relaxed blazer.',
    colors: ['#DCC9B6'],
    occasionTags: ['WORK'],
    weatherTags: ['MILD', 'COLD'],
  }),
  item({
    itemId: 'i_shoe_loafers',
    category: 'SHOE',
    name: 'Black penny loafers',
    description: 'Classic leather loafers, broken in.',
    colors: ['#1A1A1A'],
    occasionTags: ['WORK', 'CASUAL'],
    weatherTags: ['MILD', 'COLD'],
  }),
  item({
    itemId: 'i_shoe_sandals',
    category: 'SHOE',
    name: 'Strappy sandals',
    description: 'Tan leather flat sandals.',
    colors: ['#DCC9B6'],
    occasionTags: ['BRUNCH', 'BEACH'],
    weatherTags: ['HOT', 'WARM'],
  }),
  item({
    itemId: 'i_shoe_heels',
    category: 'SHOE',
    name: 'Mauve kitten heels',
    description: 'Pointed-toe slingbacks in dusty mauve.',
    colors: ['#E5D5E0'],
    occasionTags: ['DATE', 'WEDDING', 'EVENING'],
    weatherTags: ['MILD'],
  }),
  item({
    itemId: 'i_bag_tote',
    category: 'BAG',
    name: 'Cream canvas tote',
    description: 'Roomy everyday tote with leather handles.',
    colors: ['#F2EAD9'],
    occasionTags: ['CASUAL', 'WORK'],
    weatherTags: ['HOT', 'WARM', 'MILD'],
  }),
  item({
    itemId: 'i_bag_clutch',
    category: 'BAG',
    name: 'Mauve clutch',
    description: 'Small evening clutch in suede mauve.',
    colors: ['#E5D5E0'],
    occasionTags: ['EVENING', 'WEDDING'],
    weatherTags: ['MILD'],
  }),
  item({
    itemId: 'i_acc_scarf',
    category: 'ACCESSORY',
    name: 'Silk neck scarf',
    description: 'Cream-and-tan printed silk square.',
    colors: ['#F2EAD9', '#DCC9B6'],
    occasionTags: ['BRUNCH', 'WORK'],
    weatherTags: ['MILD'],
  }),
];

export const mockCombinations: Combination[] = [
  {
    comboId: 'c_sunday_brunch',
    userId: USER_ID,
    name: 'Sunday brunch',
    itemIds: ['i_dress_linen', 'i_shoe_sandals', 'i_bag_tote'],
    occasionTags: ['BRUNCH'],
    source: 'STELLA',
    createdAt: NOW,
  },
  {
    comboId: 'c_date_night',
    userId: USER_ID,
    name: 'Date night',
    itemIds: ['i_dress_floral', 'i_shoe_heels', 'i_bag_clutch'],
    occasionTags: ['DATE'],
    source: 'CRAFTED',
    createdAt: NOW,
  },
  {
    comboId: 'c_office_tue',
    userId: USER_ID,
    name: 'Office tue',
    itemIds: [
      'i_top_blouse',
      'i_bottom_jeans',
      'i_shoe_loafers',
      'i_outer_blazer',
    ],
    occasionTags: ['WORK'],
    source: 'TODAY_PICK',
    createdAt: NOW,
  },
  {
    comboId: 'c_wedding_guest',
    userId: USER_ID,
    name: 'Wedding guest',
    itemIds: [
      'i_dress_floral',
      'i_shoe_heels',
      'i_bag_clutch',
      'i_acc_scarf',
    ],
    occasionTags: ['WEDDING'],
    source: 'STELLA',
    createdAt: NOW,
  },
  {
    comboId: 'c_easy_weekend',
    userId: USER_ID,
    name: 'Easy weekend',
    itemIds: ['i_top_tee', 'i_bottom_shorts', 'i_shoe_sandals'],
    occasionTags: ['CASUAL'],
    source: 'CRAFTED',
    createdAt: NOW,
  },
];

export const mockProcessingEtaMin = 2;
